/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Steering */

#ifndef _Included_Steering
#define _Included_Steering
#ifdef __cplusplus
extern "C" {
#endif
#undef Steering_STEERING_CENTER
#define Steering_STEERING_CENTER 1400L
#undef Steering_STEERING_RIGHT_MAX
#define Steering_STEERING_RIGHT_MAX 1130L
#undef Steering_STEERING_LEFT_MAX
#define Steering_STEERING_LEFT_MAX 1670L
#undef Steering_GPIO_PIN
#define Steering_GPIO_PIN 23L
/*
 * Class:     Steering
 * Method:    turnWheels
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Steering_turnWheels
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
